In [58]:
import pandas as pd
import numpy as np

## Reindexing

In [59]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [60]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [61]:
obj2 = obj.reindex(['a', 'b', 'c', 'd','e'])

In [62]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [63]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [64]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [65]:
obj3.reindex(range(6), method='ffill') # forward-fill

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [66]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'], columns=['Ohio', 'Texas', 'California'])

In [67]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [68]:
frame2 = frame.reindex(['a','b','c','d'])

In [69]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [70]:
states = ['Texas', 'Utah', 'California']

In [71]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [72]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

## Dropping Entries from an Axis

In [73]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [74]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [75]:
new_obj = obj.drop('c')

In [76]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [77]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [78]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),index = ['Ohio','Colorado','Utah','New York'], columns=['one','two','three','four'])

In [79]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [80]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [81]:
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [82]:
data.drop(['two','four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [83]:
obj.drop('c', inplace=True)

In [84]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

## Indexing, Selection, and Filtering

In [85]:
obj = pd.Series(np.arange(4.), index=['a','b','c','d'])

In [86]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [87]:
obj['b']

1.0

In [88]:
obj[1]

1.0

In [89]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [90]:
obj[['b','c','d']]

b    1.0
c    2.0
d    3.0
dtype: float64

In [91]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [92]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [93]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [94]:
obj['b':'c'] = 5

In [95]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [96]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),index=['Ohio', 'Colorado', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])

In [97]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [98]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [99]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [100]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [101]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [102]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [103]:
data[data<5] = 0

In [104]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### Selection with loc and iloc

In [105]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [106]:
data.iloc[2, [3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [107]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [108]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [109]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [110]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

## Integer Indexes

In [111]:
ser = pd.Series(np.arange(3.))

In [112]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [113]:
ser[-1]

KeyError: -1

In [ ]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [ ]:
ser2[-1]

2.0

In [ ]:
ser[:1]

0    0.0
dtype: float64

In [ ]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [ ]:
ser.iloc[:1]

0    0.0
dtype: float64

## Arithmetic and Data Alignment

In [ ]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [ ]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [ ]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [ ]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [ ]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [ ]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'), index=['Ohio', 'Texas', 'Colorado'])

In [ ]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [ ]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [ ]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [ ]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [ ]:
df1 = pd.DataFrame({'A':[1,2]})

In [ ]:
df2 = pd.DataFrame({'B':[3,4]})

In [ ]:
df1

A
0  1
1  2

In [ ]:
df2

B
0  3
1  4

In [ ]:
df1-df2

A   B
0 NaN NaN
1 NaN NaN

### Arithmetic methods with fill values

In [ ]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),columns=list('abcd'))

In [ ]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),columns=list('abcde'))

In [ ]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [ ]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
df2.loc[1, 'b'] = np.nan

In [ ]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [ ]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [ ]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [ ]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [ ]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

## Operations betweem DataFrame and Series

In [ ]:
arr = np.arange(12.).reshape((3, 4))

In [ ]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
arr[0]

array([0., 1., 2., 3.])

In [ ]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [ ]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [ ]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [ ]:
series = frame.iloc[0]

In [ ]:
series

b    0
d    1
e    2
Name: Utah, dtype: int64

In [ ]:
frame - series

b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

In [ ]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [ ]:
series2

b    0
e    1
f    2
dtype: int64

In [ ]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [ ]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [ ]:
series3 = frame['d']

In [ ]:
series3

Utah       1
Ohio       4
Texas      7
Oregon    10
Name: d, dtype: int64

In [ ]:
frame
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [ ]:
frame.sub(series3, axis='index')

b  d  e
Utah   -1  0  1
Ohio   -1  0  1
Texas  -1  0  1
Oregon -1  0  1

## Function Application and Mapping

In [114]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [115]:
frame

b         d         e
Utah   -1.848332  0.619248 -0.954442
Ohio    1.226572  0.034229 -0.003822
Texas   0.927038 -1.634387  1.029774
Oregon  0.340462 -0.082170  1.226579

In [116]:
np.abs(frame)

b         d         e
Utah    1.848332  0.619248  0.954442
Ohio    1.226572  0.034229  0.003822
Texas   0.927038  1.634387  1.029774
Oregon  0.340462  0.082170  1.226579

In [121]:
f = lambda x : x.max() - x.min()

In [122]:
frame.apply(f)

b    3.074904
d    2.253635
e    2.181021
dtype: float64

In [123]:
frame.apply(f, axis='columns')

Utah      2.467580
Ohio      1.230394
Texas     2.664161
Oregon    1.308749
dtype: float64

In [124]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [125]:
frame.apply(f)

b         d         e
min -1.848332 -1.634387 -0.954442
max  1.226572  0.619248  1.226579

In [126]:
format = lambda x: '%.2f' % x

In [127]:
frame.applymap(format)

b      d      e
Utah    -1.85   0.62  -0.95
Ohio     1.23   0.03  -0.00
Texas    0.93  -1.63   1.03
Oregon   0.34  -0.08   1.23

In [128]:
frame['e'].map(format)

Utah      -0.95
Ohio      -0.00
Texas      1.03
Oregon     1.23
Name: e, dtype: object

## Sorting and Ranking

In [129]:
obj = pd.Series(range(4), index=['d', 'b', 'a', 'c'])

In [130]:
obj

d    0
b    1
a    2
c    3
dtype: int64

In [131]:
obj.sort_index()

a    2
b    1
c    3
d    0
dtype: int64

In [132]:
obj.sort_values()

d    0
b    1
a    2
c    3
dtype: int64

In [133]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'], columns=['d', 'a', 'b', 'c'])

In [134]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [135]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [136]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [137]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [138]:
obj = pd.Series([4,7,-3,2])

In [139]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [140]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [141]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [142]:
frame = pd.DataFrame({'b':[4,7,-3,2], 'a':[0,1,0,1]})

In [143]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [144]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [145]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [146]:
obj = pd.Series([7,-5,7,4,2,0,4])

In [147]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [148]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [149]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [150]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1],'c':[-2, 5, 8, -2.5]})

In [151]:
frame

b  a    c
0  4  0 -2.0
1  7  1  5.0
2 -3  0  8.0
3  2  1 -2.5

In [152]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

## Axis Indexed With Duplicate Labels

In [153]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [154]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [155]:
obj.index.is_unique

False

In [156]:
obj['a']

a    0
a    1
dtype: int64

In [157]:
obj['c']

4

In [158]:
df = pd.DataFrame(np.random.randn(4,3), index=['a','a','b','b'])

In [159]:
df

0         1         2
a -0.555047 -0.196332  1.924912
a -2.296887  0.105692 -0.191225
b -0.248981 -0.229210 -1.755906
b -0.500239  0.329620  1.435377

In [160]:
df.loc['b']

0        1         2
b -0.248981 -0.22921 -1.755906
b -0.500239  0.32962  1.435377