In [1]:
import numpy as np

In [2]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [3]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [4]:
cond = np.array([True, False, True, True, False])

In [5]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]

In [6]:
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [7]:
result = np.where(cond, xarr, yarr)

In [8]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [9]:
arr = np.random.randn(4,4)

In [10]:
arr

array([[-0.9429219 ,  0.7572264 ,  0.43089948,  1.06529656],
       [ 0.43694361,  1.13967801,  1.00648926, -1.48207295],
       [-0.87630948,  2.93268325, -0.0559894 ,  0.02587274],
       [-0.10711211, -0.0482809 , -0.71657478, -0.55434458]])

In [11]:
arr > 0

array([[False,  True,  True,  True],
       [ True,  True,  True, False],
       [False,  True, False,  True],
       [False, False, False, False]])

In [12]:
np.where(arr > 0, 2, -2)

array([[-2,  2,  2,  2],
       [ 2,  2,  2, -2],
       [-2,  2, -2,  2],
       [-2, -2, -2, -2]])

In [13]:
np.where(arr > 0, 2, arr)

array([[-0.9429219 ,  2.        ,  2.        ,  2.        ],
       [ 2.        ,  2.        ,  2.        , -1.48207295],
       [-0.87630948,  2.        , -0.0559894 ,  2.        ],
       [-0.10711211, -0.0482809 , -0.71657478, -0.55434458]])