In [1]:
import numpy as np

In [2]:
x = np.array([[1,2,3],[4,5,6]])

In [3]:
y = np.array([[6., 23.], [-1, 7], [8, 12]])

In [4]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8., 12.]])

In [6]:
x.dot(y)

array([[ 28.,  73.],
       [ 67., 199.]])

In [7]:
np.dot(x,y)

array([[ 28.,  73.],
       [ 67., 199.]])

In [8]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [11]:
x @ np.ones(3)

array([ 6., 15.])

In [12]:
from numpy.linalg import inv, qr

In [13]:
x = np.random.randn(5,5)

In [14]:
x

array([[-1.11229595,  1.55076515,  0.40736906,  0.24801777,  1.08984244],
       [-0.7691347 , -0.04347925,  0.90729523, -1.88305527,  0.51423534],
       [-0.54399244, -0.5281726 , -0.0908408 ,  0.64943682, -0.69183475],
       [-0.1545577 ,  1.68121676,  0.79003021, -0.17626815,  1.94858653],
       [ 0.51537711,  1.44432206, -0.86532144, -0.69859125, -1.14149307]])

In [16]:
mat = x.T

In [17]:
mat

array([[-1.11229595, -0.7691347 , -0.54399244, -0.1545577 ,  0.51537711],
       [ 1.55076515, -0.04347925, -0.5281726 ,  1.68121676,  1.44432206],
       [ 0.40736906,  0.90729523, -0.0908408 ,  0.79003021, -0.86532144],
       [ 0.24801777, -1.88305527,  0.64943682, -0.17626815, -0.69859125],
       [ 1.08984244,  0.51423534, -0.69183475,  1.94858653, -1.14149307]])

In [18]:
x.T.dot(x)

array([[ 2.41419989, -0.91962096, -1.66960261,  0.48637095, -2.12085915],
       [-0.91962096,  7.5982853 ,  0.71867404, -1.1818593 ,  3.66045198],
       [-1.66960261,  0.71867404,  2.37031518, -1.20119885,  3.50057885],
       [ 0.48637095, -1.1818593 , -1.20119885,  4.54827835, -0.6933729 ],
       [-2.12085915,  3.66045198,  3.50057885, -0.6933729 ,  7.03082574]])

In [19]:
inv(mat) # 求逆矩阵

array([[-1.21997688, -0.33383805, -2.52706706, -0.38917239,  1.18062909],
       [-0.1090386 ,  0.01466781,  0.55730605, -0.29309465, -0.27376993],
       [ 0.7397292 ,  0.88979389,  4.09856164,  1.03011651, -2.27755672],
       [ 1.12827153,  0.77603395,  3.09104124,  0.66653389, -1.25979805],
       [ 0.26378633,  0.47331939,  0.63085403,  0.00987509, -0.64232988]])

In [20]:
q, r = qr(mat) #最小二乘问题 QR分解

In [21]:
q

array([[-0.49460815, -0.22275672, -0.78020326, -0.18442506, -0.25102291],
       [ 0.68958363, -0.19260624, -0.33530553,  0.41481491, -0.45041763],
       [ 0.18114608,  0.36370003,  0.13418421, -0.67565302, -0.6003299 ],
       [ 0.11028684, -0.87683251,  0.27323302, -0.37981175, -0.00939728],
       [ 0.48462367,  0.11031463, -0.43149901, -0.43949065,  0.61125049]])

In [22]:
r

array([[ 2.24884276,  0.55632509, -0.3752667 ,  2.30378704, -0.04591844],
       [ 0.        ,  2.21753936, -0.45589831,  0.36746517, -0.22108245],
       [ 0.        ,  0.        ,  1.06530805, -1.22610071, -0.70082561],
       [ 0.        ,  0.        ,  0.        , -0.59732505,  1.8557436 ],
       [ 0.        ,  0.        ,  0.        ,  0.        , -0.95161458]])