In [1]:
import numpy as np

In [2]:
arr = np.random.randn(5,4)

In [3]:
arr

array([[ 0.77460505, -1.07295828,  0.7462147 , -0.01974396],
       [ 0.04251629,  0.94745627,  0.05611691,  0.33118753],
       [ 0.12616714, -0.4579678 ,  0.08003656,  0.11132949],
       [ 1.29467274, -1.42776219, -1.30501803, -0.90007843],
       [-0.11555308, -1.1028439 ,  0.89606235,  0.31826953]])

In [4]:
arr.mean()

-0.03386455629821891

In [5]:
np.mean(arr)

-0.03386455629821891

In [6]:
arr.sum()

-0.6772911259643782

In [7]:
arr.mean(axis = 1)

array([ 0.10702938,  0.34431925, -0.03510865, -0.58454648, -0.00101628])

In [14]:
arr[0, :]

array([ 0.77460505, -1.07295828,  0.7462147 , -0.01974396])

In [15]:
arr[0, :].mean()

0.1070293768965758

In [11]:
arr[:, 0]

array([ 0.77460505,  0.04251629,  0.12616714,  1.29467274, -0.11555308])

In [13]:
arr[:,0].sum()

2.122408139190443

In [8]:
arr.sum(axis = 0)

array([ 2.12240814, -3.11407591,  0.47341248, -0.15903584])

In [16]:
arr = np.array([0,1,2,3,4,5,6,7])

In [17]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [19]:
arr = np.array([[0,1,2],[3,4,5],[6,7,8]])

In [20]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [23]:
arr.cumsum(axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])

In [24]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])