In [2]:
import numpy as np

In [3]:
data = np.random.randn(2, 3)

In [4]:
data

array([[ 0.89013   , -1.54136297, -0.4420219 ],
       [ 0.41761599, -1.21856359, -0.61271476]])

In [5]:
data * 10

array([[  8.90130003, -15.4136297 ,  -4.42021899],
       [  4.17615994, -12.18563591,  -6.12714761]])

In [6]:
data + data

array([[ 1.78026001, -3.08272594, -0.8840438 ],
       [ 0.83523199, -2.43712718, -1.22542952]])

In [7]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

## Creating ndarrays

In [9]:
data1 = [6, 7.5, 8, 0, 1]

In [10]:
arr1 = np.array(data1)

In [11]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [12]:
arr1.ndim, arr1.shape, arr1.dtype

(1, (5,), dtype('float64'))

In [13]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [14]:
arr2 = np.array(data2)

In [15]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr2.ndim, arr2.shape, arr2.dtype

(2, (2, 4), dtype('int64'))

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
np.empty((2,3,2))

array([[[-3.10503618e+231, -3.10503618e+231],
        [ 3.45845952e-323,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000]],

       [[-3.10503618e+231, -3.10503618e+231],
        [ 1.97626258e-323,  0.00000000e+000],
        [ 0.00000000e+000,  8.34402697e-309]]])

In [20]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
np.full((3,3), 3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

## Data Types for ndarrays

In [22]:
arr1 = np.array([1,2,3], dtype=np.float64)

In [23]:
arr1.dtype

dtype('float64')

In [24]:
arr2 = np.array([1,2,3], dtype=np.int32)

In [25]:
arr2.dtype

dtype('int32')

In [26]:
arr = np.array([1, 2, 3, 4, 5])

In [27]:
arr.dtype

dtype('int64')

In [28]:
float_arr = arr.astype(np.float64)

In [29]:
float_arr.dtype

dtype('float64')

In [30]:
arr = np.array([3.7, -1.2, -2.6, 0.0, 1.9, 10.1])

In [31]:
arr

array([ 3.7, -1.2, -2.6,  0. ,  1.9, 10.1])

In [32]:
arr.astype(np.int32)

array([ 3, -1, -2,  0,  1, 10], dtype=int32)

In [33]:
numeric_strings = np.array(['1.23', '-9.01', '42'], dtype=np.string_)

In [34]:
numeric_strings.astype(float)

array([ 1.23, -9.01, 42.  ])

In [35]:
int_array = np.arange(10)

In [36]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [37]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [38]:
empty_uint32 = np.empty(8, dtype='u4')

In [39]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

## Arithmetic with NumPy Arrays

In [40]:
arr = np.array([[1,2,3],[4,5,6]])

In [41]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [43]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [44]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [45]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [46]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])

In [47]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [48]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

## Basic Indexing and Slicing

In [49]:
arr = np.arange(10)

In [50]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr[5]

5

In [52]:
arr[5:8]

array([5, 6, 7])

In [53]:
arr[5:8]=12

In [54]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [55]:
arr_slice = arr[5:8]

In [56]:
arr_slice

array([12, 12, 12])

In [57]:
arr_slice[1] = 12345

In [58]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [59]:
arr_slice[:] = 64

In [60]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [61]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [62]:
arr2d[2]

array([7, 8, 9])

In [63]:
arr2d.shape

(3, 3)

In [64]:
arr2d[0][2]

3

In [66]:
arr2d[0,2]

3

In [82]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [83]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [84]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
old_values = arr3d[0].copy()

In [86]:
arr3d[0]=42

In [87]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [88]:
arr3d[0]=old_values

In [89]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [90]:
arr3d[1,0]

array([7, 8, 9])

In [91]:
x = arr3d[1]

In [92]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [93]:
x[0]

array([7, 8, 9])

## Indexing with slices

In [95]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [96]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [97]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [101]:
arr2d[1, :2]

array([4, 5])

In [102]:
arr2d[:2,2]

array([3, 6])

In [103]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [104]:
arr2d[:2, 1:] = 0

In [105]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## Boolean Indexing

In [115]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [116]:
data = np.random.randn(7,4)

In [117]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [118]:
data

array([[ 0.27262555,  0.39520763,  0.44105382,  0.66946498],
       [-0.13555849, -0.22804475, -0.14943442, -1.64972412],
       [ 1.01673406,  0.37498921,  0.33615875,  0.17697364],
       [ 2.01617209,  0.54582683,  0.87388255, -0.60050203],
       [ 2.41287072, -0.10856523,  0.15356364, -0.95486643],
       [-0.60956163,  0.29943392,  1.01193283, -0.69067831],
       [ 0.71208786, -0.86799719, -1.22615719,  0.36613039]])

In [119]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [120]:
data[names=='Bob']

array([[ 0.27262555,  0.39520763,  0.44105382,  0.66946498],
       [ 2.01617209,  0.54582683,  0.87388255, -0.60050203]])

In [121]:
data[names=='Bob', 2:]

array([[ 0.44105382,  0.66946498],
       [ 0.87388255, -0.60050203]])

In [122]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [123]:
data[~(names == 'Bob')]

array([[-0.13555849, -0.22804475, -0.14943442, -1.64972412],
       [ 1.01673406,  0.37498921,  0.33615875,  0.17697364],
       [ 2.41287072, -0.10856523,  0.15356364, -0.95486643],
       [-0.60956163,  0.29943392,  1.01193283, -0.69067831],
       [ 0.71208786, -0.86799719, -1.22615719,  0.36613039]])

In [124]:
cond = names == 'Bob'

In [125]:
data[~cond]

array([[-0.13555849, -0.22804475, -0.14943442, -1.64972412],
       [ 1.01673406,  0.37498921,  0.33615875,  0.17697364],
       [ 2.41287072, -0.10856523,  0.15356364, -0.95486643],
       [-0.60956163,  0.29943392,  1.01193283, -0.69067831],
       [ 0.71208786, -0.86799719, -1.22615719,  0.36613039]])

In [126]:
mask = (names == 'Bob') | (names == 'Will')

In [127]:
mask

array([ True, False,  True,  True,  True, False, False])

In [128]:
data[mask]

array([[ 0.27262555,  0.39520763,  0.44105382,  0.66946498],
       [ 1.01673406,  0.37498921,  0.33615875,  0.17697364],
       [ 2.01617209,  0.54582683,  0.87388255, -0.60050203],
       [ 2.41287072, -0.10856523,  0.15356364, -0.95486643]])

In [130]:
data[data < 0] = 0

In [131]:
data

array([[0.27262555, 0.39520763, 0.44105382, 0.66946498],
       [0.        , 0.        , 0.        , 0.        ],
       [1.01673406, 0.37498921, 0.33615875, 0.17697364],
       [2.01617209, 0.54582683, 0.87388255, 0.        ],
       [2.41287072, 0.        , 0.15356364, 0.        ],
       [0.        , 0.29943392, 1.01193283, 0.        ],
       [0.71208786, 0.        , 0.        , 0.36613039]])

In [132]:
data[names != 'Joe'] = 7

In [133]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.29943392, 1.01193283, 0.        ],
       [0.71208786, 0.        , 0.        , 0.36613039]])

## Fancy Indexing

In [134]:
arr = np.empty((8,4))

In [135]:
for i in range(8):
    arr[i] = i

In [136]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [137]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [138]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [141]:
arr = np.arange(32).reshape(8, 4)

In [142]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [143]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [144]:
arr[[1,5,7,2]][:, [0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

## Transposing Arrays and Swapping Axes

In [145]:
arr = np.arange(15).reshape(3, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [146]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [147]:
arr = np.random.randn(6,3)

In [148]:
arr

array([[ 0.38859266, -0.30345388,  2.46792773],
       [ 0.0415302 , -1.03348797, -0.01973102],
       [-0.77494767, -0.51479413,  1.67850999],
       [ 1.5311756 ,  1.10972427,  0.85977128],
       [-1.05042924,  1.08980929, -0.02989044],
       [-0.057035  ,  0.56136025,  0.24957666]])

In [149]:
arr.T

array([[ 0.38859266,  0.0415302 , -0.77494767,  1.5311756 , -1.05042924,
        -0.057035  ],
       [-0.30345388, -1.03348797, -0.51479413,  1.10972427,  1.08980929,
         0.56136025],
       [ 2.46792773, -0.01973102,  1.67850999,  0.85977128, -0.02989044,
         0.24957666]])

In [150]:
np.dot(arr.T, arr)

array([[ 4.20442619,  0.7604956 ,  0.99106576],
       [ 0.7604956 ,  4.1594922 , -0.53096096],
       [ 0.99106576, -0.53096096,  9.71084097]])

In [153]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [158]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [166]:
arr
arr.shape

(2, 2, 4)

In [160]:
arr.swapaxes(1,2) #将第2个维度和第三个维度互换

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [161]:
arrt1 = np.arange(4).reshape(2,2)

In [162]:
arrt1

array([[0, 1],
       [2, 3]])

In [163]:
arrt1.transpose((0,1))

array([[0, 1],
       [2, 3]])

In [164]:
arrt1.transpose(1,0)

array([[0, 2],
       [1, 3]])