In [2]:
import numpy as np

In [3]:
arr = np.random.randn(6)

In [4]:
arr

array([ 3.24813071, -0.39064853,  1.66785306, -0.52975341,  0.25376199,
       -2.0740546 ])

In [5]:
arr.sort()

In [6]:
arr

array([-2.0740546 , -0.52975341, -0.39064853,  0.25376199,  1.66785306,
        3.24813071])

In [7]:
arr = np.random.randn(5,3)

In [8]:
arr

array([[ 0.88818906, -0.76101053,  1.18966045],
       [-0.39654342, -1.26065209,  0.93030991],
       [-0.04541213, -0.08821829,  0.57418304],
       [-0.81859172, -0.01076459, -1.16247933],
       [ 0.85454645,  0.1313322 ,  1.00555671]])

In [9]:
arr.sort(1)

In [10]:
arr

array([[-0.76101053,  0.88818906,  1.18966045],
       [-1.26065209, -0.39654342,  0.93030991],
       [-0.08821829, -0.04541213,  0.57418304],
       [-1.16247933, -0.81859172, -0.01076459],
       [ 0.1313322 ,  0.85454645,  1.00555671]])

In [11]:
large_arr = np.random.randn(1000)

In [12]:
large_arr.sort()

In [13]:
large_arr[int(0.05*len(large_arr))]

-1.5671207817999155