In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [6]:
x = np.random.randn(8)

In [7]:
y = np.random.randn(8)

In [8]:
x

array([-1.26673454,  0.16916912, -0.64229441,  0.25862   , -0.52336712,
       -0.78688903, -0.79603907, -1.8637111 ])

In [9]:
y

array([ 0.57919135, -1.05306884, -0.06832598,  0.27654552, -0.38381032,
       -2.3251095 , -3.45511113,  1.1012119 ])

In [10]:
np.maximum(x, y)

array([ 0.57919135,  0.16916912, -0.06832598,  0.27654552, -0.38381032,
       -0.78688903, -0.79603907,  1.1012119 ])

In [11]:
arr = np.random.randn(7)*5

In [12]:
arr

array([-0.26688171,  7.30425548,  4.31998805, -3.50030064, -1.13671997,
        0.31370185,  6.44146313])

In [13]:
remainder, whole_part = np.modf(arr)

In [14]:
remainder

array([-0.26688171,  0.30425548,  0.31998805, -0.50030064, -0.13671997,
        0.31370185,  0.44146313])

In [15]:
whole_part

array([-0.,  7.,  4., -3., -1.,  0.,  6.])

In [16]:
arr

array([-0.26688171,  7.30425548,  4.31998805, -3.50030064, -1.13671997,
        0.31370185,  6.44146313])

In [17]:
np.sqrt(arr)

/var/folders/s0/q2ttb3y11qj2hy6gvy2wjq640000gn/T/ipykernel_81461/2296558006.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([       nan, 2.70263861, 2.0784581 ,        nan,        nan,
       0.56009093, 2.53800377])

In [18]:
np.sqrt(arr, arr)

/var/folders/s0/q2ttb3y11qj2hy6gvy2wjq640000gn/T/ipykernel_81461/269955669.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([       nan, 2.70263861, 2.0784581 ,        nan,        nan,
       0.56009093, 2.53800377])

In [19]:
arr

array([       nan, 2.70263861, 2.0784581 ,        nan,        nan,
       0.56009093, 2.53800377])